[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
bindeps = true

[build]
target = ".cargo/x86_64-rust_OS.json"

# [target.'cfg(target_os = "none")']
# runner = "bootimage runner"
