name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt-get install -y qemu-system-x86
    - name: Install rustup
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly
    - name: Install rust-nightly
      run: rustup default nightly
    - name: Build
      run: cargo run --verbose
    - name: Run tests
      run: cargo test --verbose
